### ISSUE TITLE
Basic - Weather Forecast Page

### ISSUE THREAD

**Issue by lelandtran** [CodePathDreamTeam/GroupProject#4]
> As a user, I want to be able to check the weather of any given location (defaulting with my current location) for a few days ahead so I can plan accordingly

**Acceptance Criteria: The user can select a city, and the app displays the temperature and weather conditions for the next three days**

**Comment by baubrey91** [comment]
API client for weather station has been set up via the wunderground api

**Comment by lelandtran** [comment]
Changes made in pull request #8
