### ISSUE TITLE
Basic - Points of Interest

### ISSUE THREAD

**Issue by lelandtran** [CodePathDreamTeam/GroupProject#7]
> As a traveler, I'd like to be able to explore the different possible points of interest in the area I am visiting or am considering visiting

**Acceptance Criteria: The user can see a list of points of interest in a location they specify**

**Comment by baubrey91** [comment]
Map and augmented reality implementation is complete. Filter for type of POI and ui polish is not complete. Also need to test map delocation after leaving view to save battery
